version: '3'
services:

  config:
    container_name: config
    image: pabloluduvichack/microservices-config:1.0
    restart: always
    environment:
      URI: 'https://github.com/pluduvichack/microservices.git'
    ports:
    - 8888:8888
    expose:
      - 8888

  discovery:
    container_name: discovery
    image: pabloluduvichack/microservices-discovery:1.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
    ports:
      - 8761:8761
    expose:
      - 8761
    depends_on:
      - config

  jms:
    container_name: jms
    image: rmohr/activemq
    restart: always
    ports:
      - 6161:61616
      - 8161:8161
    expose:
      - 6161
      - 8161

  gateway:
    container_name: gateway
    image: pabloluduvichack/microservices-gateway:1.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
      EUREKA_URL: 'http://discovery:8761/eureka/'
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - config
      - discovery