version: '3'
services:

  trace:
    container_name: trace
    image: openzipkin/zipkin
    restart: always
    ports:
      - 9411:9411
    expose:
      - 9411

  config:
    container_name: config
    image: pabloluduvichack/microservices-config:1.0
    restart: always
    environment:
      URI: 'https://github.com/pluduvichack/microservices.git'
    ports:
    - 8888:8888
    expose:
      - 8888

  discovery:
    container_name: discovery
    image: pabloluduvichack/microservices-discovery:1.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
    ports:
      - 8761:8761
    expose:
      - 8761
    depends_on:
      - config

  jms:
    container_name: jms
    image: rmohr/activemq
    restart: always
    ports:
      - 6161:61616
      - 8161:8161
    expose:
      - 6161
      - 8161

  produtos:
    container_name: produtos
    image: pabloluduvichack/microservices-produtos:2.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
      EUREKA_URL: 'http://discovery:8761/eureka/'
      JMS_URL: 'tcp://jms:61616'
      ZIPKIN_URL: 'http://trace:9411/'
    ports:
      - 8081:8081
    depends_on:
      - config
      - discovery
      - jms

  gateway:
    container_name: gateway
    image: pabloluduvichack/microservices-gateway:1.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
      EUREKA_URL: 'http://discovery:8761/eureka/'
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - config
      - discovery

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    hostname: mysql
    environment:
      MYSQL_DATABASE: 'vendas'
      MYSQL_USER: 'vendas'
      MYSQL_PASSWORD: 'vendas123'
      MYSQL_ROOT_PASSWORD: 'vendas123'
    ports:
      - 3307:3306
    expose:
      - 3307

  redis:
    container_name: redis
    image: redis
    restart: always
    hostname: redis
    ports:
      - 6379:6379
    expose:
      - 6379